# Generated by Django 2.1.4 on 2018-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0002_auto_20181212_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='adgroups',
            name='user',
        ),
        migrations.AlterField(
            model_name='adgroups',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
