# Generated by Django 2.1.4 on 2018-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0003_auto_20181212_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroups',
            name='user',
            field=models.ManyToManyField(to='aduser.aduser'),
        ),
    ]
