# Generated by Django 2.1.4 on 2018-12-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('aduser', '0004_adgroups_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroups',
            name='group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.Group'),
        ),
    ]
