# Generated by Django 2.1.4 on 2018-12-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0006_auto_20181212_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='group',
        ),
    ]
