# Generated by Django 2.1.4 on 2018-12-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0008_adgroups_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='group',
        ),
    ]
