# Generated by Django 2.1.4 on 2018-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0010_adgroups_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduser',
            name='telephoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
