# Generated by Django 2.1.4 on 2018-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0011_aduser_telephonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduser',
            name='password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aduser',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
