# Generated by Django 2.1.4 on 2018-12-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0012_auto_20181213_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aduser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='aduser',
            name='username',
        ),
    ]
