# Generated by Django 2.1.4 on 2019-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cisco', models.CharField(blank=True, max_length=50, null=True)),
                ('ciscotag', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=45, null=True)),
                ('field_version', models.IntegerField(blank=True, db_column='@version', null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=20, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('field_timestamp', models.DateTimeField(blank=True, db_column='@timestamp', null=True)),
                ('syslog_pri', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'connections',
                'managed': False,
            },
        ),
    ]
