# Generated by Django 2.1.4 on 2018-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astdb',
            fields=[
                ('key', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'astdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('calldate', models.DateTimeField(primary_key=True, serialize=False)),
                ('clid', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('dcontext', models.CharField(max_length=80)),
                ('channel', models.CharField(max_length=80)),
                ('dstchannel', models.CharField(max_length=80)),
                ('lastapp', models.CharField(max_length=80)),
                ('lastdata', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=45)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('userfield', models.CharField(max_length=255)),
                ('did', models.CharField(max_length=50)),
                ('recordingfile', models.CharField(max_length=255)),
                ('cnum', models.CharField(max_length=80)),
                ('cnam', models.CharField(max_length=80)),
                ('outbound_cnum', models.CharField(max_length=80)),
                ('outbound_cnam', models.CharField(max_length=80)),
                ('dst_cnam', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'cdr',
                'managed': False,
            },
        ),
    ]
