# Generated by Django 2.1.4 on 2019-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuesConfig',
            fields=[
                ('extension', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=35)),
                ('grppre', models.CharField(max_length=100)),
                ('alertinfo', models.CharField(max_length=254)),
                ('ringing', models.IntegerField()),
                ('maxwait', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=20)),
                ('ivr_id', models.CharField(max_length=8)),
                ('dest', models.CharField(max_length=50)),
                ('cwignore', models.IntegerField()),
                ('queuewait', models.IntegerField(blank=True, null=True)),
                ('use_queue_context', models.IntegerField(blank=True, null=True)),
                ('togglehint', models.IntegerField(blank=True, null=True)),
                ('qnoanswer', models.IntegerField(blank=True, null=True)),
                ('callconfirm', models.IntegerField(blank=True, null=True)),
                ('callconfirm_id', models.IntegerField(blank=True, null=True)),
                ('qregex', models.CharField(blank=True, max_length=255, null=True)),
                ('agentannounce_id', models.IntegerField(blank=True, null=True)),
                ('joinannounce_id', models.IntegerField(blank=True, null=True)),
                ('monitor_type', models.CharField(blank=True, max_length=5, null=True)),
                ('monitor_heard', models.IntegerField(blank=True, null=True)),
                ('monitor_spoken', models.IntegerField(blank=True, null=True)),
                ('callback_id', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'queues_config',
                'managed': False,
            },
        ),
    ]
